[build]
  # Build command
  command = "ng build --configuration=production"

  # Output directory
  publish = "dist/resort-plus"

  # Base directory for build
  base = "apps/frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "20.12.0"

  # Package manager
  NPM_FLAGS = "--version"

# Redirect rules for Angular routing
[[redirects]]
  from = "/api/*"
  to = "${API_ORIGIN}/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript and CSS files
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
